aws_region = "us-east-1"
vpc_cidr = "10.10.0.0/16"
public_subnet1_cidr = "10.10.1.0/24"
vpc_name = "terraform-aws-prod"
IGW_name = "terraform-aws-prod-igw"
public_subnet1_name = "Terraform_Public_Subnet1-Prod"
Main_Routing_Table = "Terraform_Main_table-Prod"
key_name = "LaptopKey"
